import PickMeals from "../assets/pick-meals-image.png";
import ChooseMeals from "../../assets/choose-image.png";
import DeliveryMeals from "../../assets/delivery-image.png";

export const workInfoData = [
  {
    image: PickMeals,
    title: "Elegir Comidas",
    text: "Lorem ipsum dolor sit amet consectetur. Maecenas orci et sagittis duis elementum interdum facilisi bibendum.",
  },
  {
    image: ChooseMeals,
    title: "Elegir Con Qué Frecuencia",
    text: "Lorem ipsum dolor sit amet consectetur. Maecenas orci et ",
  },
  {
    image: DeliveryMeals,
    title: "Entregas Rápidas",
    text: "Lorem ipsum dolor sit amet consectetur. Maecenas orci et lorem ipsum",
  },
];
